[deployment]
site_id = "blake"

[deployment.observed]
checked_at = "2026-09-11T15:11:50+00:00"

[deployment.observed.dns_target]

[[deployment.observed.dns_target.records]]
name = "@"
record_type = "A"
ttl = 3600
value = "45.76.13.224"

[[deployment.observed.dns_target.records]]
name = "www"
record_type = "A"
ttl = 3600
value = "45.76.13.224"

[deployment.targets."moss:blake"]
last_deployed_generation_id = "edf4f7cc743a234c"
last_deployment_at = "2026-09-11T15:11:50+00:00"
last_deployment_url = "https://blake.mosspub.com"
